name: Build Windows VST3 & AAX

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
    
    - name: Setup CMake
      uses: lukka/get-cmake@latest
    
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Release --parallel 4
    
    - name: List Build Output
      run: |
        cd build
        echo "Build artifacts:"
        ls -la TheKingsCab_artefacts/Release/
        echo "VST3:"
        ls -la TheKingsCab_artefacts/Release/VST3/
        echo "AAX:"
        ls -la TheKingsCab_artefacts/Release/AAX/
    
    - name: Upload VST3
      uses: actions/upload-artifact@v4
      with:
        name: Windows-VST3
        path: build/TheKingsCab_artefacts/Release/VST3/
    
    - name: Upload AAX
      uses: actions/upload-artifact@v4
      with:
        name: Windows-AAX
        path: build/TheKingsCab_artefacts/Release/AAX/
