name: Build macOS AU and VST3

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake Ninja Release)
        run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release -DJUCE_BUILD_EXAMPLES=OFF -DJUCE_BUILD_EXTRAS=OFF -DJUCE_FETCH_VST3_SDK=ON

      - name: Build (Release)
        run: cmake --build build --config Release --parallel

      - name: Zip AU and VST3
        run: |
          mkdir -p artifacts
          /usr/bin/zip -r artifacts/Multi-Blend-macOS-VST3.zip build/CrossFX_artefacts/Release/VST3/Multi-Blend.vst3
          /usr/bin/zip -r artifacts/Multi-Blend-macOS-AU.zip   build/CrossFX_artefacts/Release/AU/Multi-Blend.component

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Multi-Blend-macOS
          path: artifacts/*
          if-no-files-found: error


